# Generated by Django 5.1.5 on 2025-01-26 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
                'indexes': [
                    models.Index(fields=['name'], name='idx_source_name'),
                    models.Index(fields=['url'], name='idx_source_url'),
                ],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('criteria_status', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to='jobs.source'
                    ),
                ),
            ],
            options={
                'db_table': 'job_descriptions',
                'indexes': [
                    models.Index(fields=['title'], name='idx_job_title'),
                    models.Index(fields=['is_analyzed'], name='idx_job_is_analyzed'),
                ],
            },
        ),
        migrations.CreateModel(
            name='GithubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='github_tasks', to='jobs.source'
                    ),
                ),
            ],
            options={
                'db_table': 'github_tasks',
                'indexes': [
                    models.Index(fields=['source'], name='idx_source_id'),
                    models.Index(fields=['created_at'], name='idx_created_at'),
                    models.Index(fields=['updated_at'], name='idx_updated_at'),
                ],
            },
        ),
    ]
