# Generated by Django 5.1.5 on 2025-01-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='is_sanitized',
            field=models.BooleanField(default=False),
        ),
    ]
