services:
  postgres:
    image: postgres:15-alpine
    container_name: job_finder_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: job_finder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: job_finder_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local